### ISSUE TITLE
write tutorial for CSS-based user muting 

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3133]
I thought we had a tutorial for CSS-based user muting somewhere, but a support request made me realize we either don't or it's not somewhere any of us can easily find it! so, a tutorial on CSS-based user muting (for comments and entries) and when it will/won't work (ie, "it won't work on site-skinned comment pages") that can be replaced by instructions on native user muting when we finally finish the sispyhean prerequisites and can implement that.

**Comment by cmho** [comment]
The following are intended for most modern dreamwidth site layouts; however, some older layouts and third-party custom S2 builds will need different classnames, since they're not built off of the same markup. Also note that these tricks will not work if you're using the site on your mobile device, since they require addons to function.

## CSS Methods

You'll want something like the Stylus addon ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/styl-us/), [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)) to implement these. You'll want to click the "Write a New Style" button and select "All URLs on the domain" and enter "dreamwidth.com" in the provided textbox.

### Simple Version

Replace `[username]` in the snippet below to completely hide all entries and comments by a particular user. Note that this will leave gaps in comment chains, and won't hide comments by other users that mention that user. (e.g., if someone mentions that they wrote this fic for [user you hate], you'll still see it on your read page/in the community.)

```css
.poster-[username] { 
  display: none;
}
```

### Fancy Version

The following snippet (remember to replace [username]) will leave entries and comments on the page, but will apply a blur filter and an overlay to the content and a text message that says that you've muted the user. You might want to use this if you want to be able to know the posts are there, but don't want to be able to see the actual content, similar to how some of Tumblr XKit's muting works.

```css
.poster-[username] {
  position: relative;
  overflow: hidden;
}

.poster-[username]:before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0,0,0,.5);
}

.poster-[username]:after {
  content: "You muted this user";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.poster-[username] .comment,
.poster-[username] .entry {
  filter: blur(10px);
}
```
